### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by aalavender** [wHyEt/Awtrix2-Docker#10]
awtrix | Connecting to blueforcer.de (213.136.87.88:443)
awtrix | ssl_client: blueforcer.de: certificate verification failed: certificate has expired

**Comment by DjVari** [comment]
I have the same issue.

**Comment by ghost** [comment]
https://github.com/wHyEt/Awtrix2-Docker/issues/9#issue-1013734161

**Comment by wHyEt** [comment]
Same as #9 please follow up there. Thank you

**Comment by JamesNolan17** [comment]
Same Issue!

**Comment by wHyEt** [comment]
@JamesNolan17 Issue is already solved in #9

**Comment by YanYan233** [comment]
> 

请问有解决办法了吗，openwrt的docker一直无法运行，我看这位up的说法是文件不对，我把他的文件啥上传进data里还是不对。。。
https://b23.tv/GTiAkHe

**Comment by YanYan233** [comment]
> awtrix | Connecting to blueforcer.de (213.136.87.88:443)
> awtrix | ssl_client: blueforcer.de: certificate verification failed: certificate has expired

请问有解决办法了吗，openwrt的docker一直无法运行，我看这位up的说法是文件不对，我把他的文件啥上传进data里还是不对。。。
https://b23.tv/GTiAkHe

**Comment by wHyEt** [comment]
@YanYan233 Problem has been solved already. See posts above. Also I don't speak chinese.

**Comment by YanYan233** [comment]
> @YanYan233 Problem has been solved already. See posts above. Also I don't speak chinese.

thank you.
 Maybe China's Internet is slow, ‘awtrix.jar’ this file download too slow.
I use '-e AUTOUPDATE=false', and manual download "https://blueforcer.de/awtrix/stable/awtrix.jar"
upload to docker，then successed！
