### ISSUE TITLE
Image not working on older PIs

### ISSUE THREAD

**Issue by soebbing** [wHyEt/Awtrix2-Docker#12]
Hi! 

I just wanted to give a little heads up to users of older PIs: I tried to run the image (thanks, @wHyEt !), but it always crashed without any real hint to why.

After trying to install the software directly, I realized that current JREs aren't supporting the CPUs of old PIs like mine anymore:

```
cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2835
Revision        : 000e
Serial          : 00000000edd4a99c
Model           : Raspberry Pi Model B Rev 2
```

I got around this issue by using a 32bit version of Azul's OpenJDK (https://www.azul.com/downloads/?version=java-11-lts&os=linux&architecture=arm-32-bit-hf&package=jdk#download-openjdk)

Maybe it would be possible to create a Docker image for old PIs as well? I understand that it might need some extra work, because there might not be a fitting base image to start from.

In any case, thanks again for your image! And have a great day!
Hendrik

**Comment by wHyEt** [comment]
Hi Hendrik.

Thanks for the Info. Yes older platforms were never supported by my build there was no need bevor. But I will look into it. Wenn I have some time. Thanks for the update :)

Greetings
Nick
