### ISSUE TITLE
Allow Specifying Host IP

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [wHyEt/Awtrix2-Docker#13]
When using the Awtrix dashboard to API calls, I am receiving an error that the client is disconnected. I believe that this is due to the browser using the docker IP to execute the command rather than using the host.

It would be great if there was a way to specify the host IP either as a bind mount (similar to what is done with the host MAC address for premium) or as an environment variable

**Comment by wHyEt** [comment]
You can use standard Docker methods. To assign any ip Address to the Container. or run it in host mode. There is no ned for an env variable for IP

**Comment by danieledwardgeorgehitchcock** [comment]
I am already assigning the ip via the standard docker methods and don't particularly want to use host networking as it removes the isolation between the dockerised app.

The issue I am facing is that when connecting to the Web ui via the host address (I.e. 192.168.1.x), everything works apart from the "test API call" feature as this points to the docker address.

My request is not for changing the ip of the container, just to use an environment variable / mapped file to url rewrite the test API call

**Comment by wHyEt** [comment]
The host will allways take the ip where its hosted. I have no posibillity to influance that. The API works also you can test this with a simple curl command: 
curl -d {"force":true,"text":"Awesome","icon":1,"color":[0,255,255],"count":2} -H "Content-Type: application/json" -X POST http://192.168.1.xxx:7000/api/v3/notify
{ "success" : "true" }
