### ISSUE TITLE
wget: server returned error: HTTP/1.1 404 Not Found

### ISSUE THREAD

**Issue by JamesNolan17** [wHyEt/Awtrix2-Docker#14]
The container was operating well until today.
Connecting to blueforcer.de（213.136.87.88:443）
wget: server returned error: HTTP/1.1 404 Not Found

**Comment by wHyEt** [comment]
was an error on the bluforcer server should run back as it was but I suggest saving the jar and turn of autoupdate since awtrix2 is not maintained anymore.
