### ISSUE TITLE
Redownload awtrix.jar every time when the container restart

### ISSUE THREAD

**Issue by WilsonXu0512** [wHyEt/Awtrix2-Docker#7]
Hi sir,
I use your Awtrix2-Docker on Synology NAS,
Everytime I restart or reboot the device, the docker will redownload **awtrix.jar** from a Germany Server(213.136.87.88:443)
I'm in China and I think you know our Internet environment :( ,  It will take a long time and always fail.
Would please do some change to skip this step?
![无标题](https://user-images.githubusercontent.com/80147765/111643583-0a773f80-883a-11eb-8ab1-0c30dd9c9628.png)

**Comment by CWempe** [comment]
Have a look at the [README](https://github.com/wHyEt/Awtrix2-Docker#autoupdate):

I think there is already an option to disable `Autoupdate` via an envoronment variable.

**Comment by wHyEt** [comment]
Hey 😄 
yes there is an env Variable what you can set to dissble the Auto Update 

-e AUTOUPDATE=false 

Greetings 

wHyEt

**Comment by WilsonXu0512** [comment]
Thanks bro，It's ok after dissble  AutoUpdate
