### ISSUE TITLE
open /opt/docker/tmp/GetImageBlob800938051: no such file or directory

### ISSUE THREAD

**Issue by CuewarsTaner** [wHyEt/Awtrix2-Docker#8]
![image](https://user-images.githubusercontent.com/46869194/111921107-bdab9700-8acd-11eb-901c-8d3edb7aa16a.png)

**Comment by CuewarsTaner** [comment]
![image](https://user-images.githubusercontent.com/46869194/111921120-cb611c80-8acd-11eb-9b74-670d31eb2692.png)

**Comment by wHyEt** [comment]
This is to less Information to debug the error. It Looks like the Container is not Even pulled so that has nothing to do with the Container. Could be that your Hardware is Not compatible.
